# App info pages on digirunestudios.com/<slug>/ : content data.
# Every fact below comes from the LIVE App Store listing (read via API 2026-10-05,
# saved _cowork/_pickup-2026-10-03/store-only-2026-10-05/live-apple-listings.json).
# DigiRune-written copy: no em dashes. Publisher names and marks verbatim.

APPS = {
 'mercs': dict(
  name='MERCS Companion',
  game='MERCS 2.5',
  publisher='Fifth Angel Studios',
  title='MERCS Companion: the Official MERCS 2.5 Field Companion App',
  meta='The official companion app for MERCS 2.5. All 12 MegaCons, 123 units, every Contingency card, all ten Operations and the full core rules, offline. No ads. No subscription. Pay once.',
  accent='#3FB8C0', accent2='#8FE0E4', glow='rgba(63,184,192,.30)', tint='#0E2422',
  eyebrow='Official Field Companion',
  h1='MERCS<br>Companion',
  tagline='Every unit. Every card. Every mission.',
  lede='The official companion app for MERCS 2.5: your complete tactical reference, at the table and off. Every model, card, mission and rule from the game you own, organized to find in a tap and built to work with no signal.',
  pills=['No ads', 'No subscription', 'Works offline'],
  apple='https://apps.apple.com/app/mercs-companion-wargame-rules/id6794927606',
  play='https://play.google.com/store/apps/details?id=com.digirunestudios.mercs',
  icon='../assets/icon-mercs.webp',
  feature='../assets/apps/mercs-feature.webp',
  video='../mercs-demo.mp4', poster='../mercs-demo-poster.jpg',
  shots=[
   ('mercs-shot-1', 'Your official MERCS companion'),
   ('mercs-shot-2', 'All 123 units, every stat and weapon'),
   ('mercs-shot-3', 'No ads. No subscription. Pay once, yours forever.'),
   ('mercs-shot-4', 'Build a legal strike team'),
   ('mercs-shot-5', 'Draw contingencies live at the table'),
   ('mercs-shot-6', 'Run all ten operations, briefed in full'),
   ('mercs-shot-7', 'All 12 MegaCons, one tap away'),
   ('mercs-shot-8', 'Master every corp and its traits'),
  ],
  kicker='MERCS 2.5',
  inside_title="What's inside",
  inside=[
   ('12 MegaCons, 123 units', 'Full stat lines, weapons and abilities, plus the real Reference Card front and back.'),
   ('Every Contingency deck', 'Card by card: 19 shared cards plus each MegaCon’s faction-unique card, verbatim.'),
   ('Corporate Traits', 'For all 12 MegaCons: the faction-wide rules and tables that always apply.'),
   ('All ten Operations', 'Briefed in full: briefings, parameters and secured objectives, with battle maps for featured operations.'),
   ('The complete rules', 'The MERCS 2.5 core ruleset plus the Recon add-on, the modifier tables and a searchable glossary.'),
  ],
  tools_title='Seven battlefield tools, plus Favorites',
  tools=[
   ('Strike Team Builder', 'Build a legal team with a live legality check.'),
   ('Contingency Draw', 'Deal and manage a real hand during play.'),
   ('Operation Setup', 'Track parameters and score objectives live.'),
   ('Round Tracker', 'Initiative and activation order, Quick handled for you.'),
   ('Damage & Armor', 'Blood pips and armor checks, no math.'),
   ('MERCS Codex', 'A color-coded stat heatmap across the whole game.'),
   ('Compare Units', 'Stack two or three models side by side.'),
  ],
  built_title='Built the way it should be',
  built=[
   'No ads. No subscription. No tracking. Pay once, yours forever.',
   'Works fully offline, there when the table has no signal.',
   'Optional sign-in syncs your teams, trackers and favorites across devices.',
   'Universal search finds any unit, card, mission, rule or keyword instantly.',
  ],
  extra=None,
  credit='An official DigiRune Studios companion for MERCS 2.5. MERCS™ © Fifth Angel Studios, used under license.',
 ),
 'twisted': dict(
  name='Twisted Companion App',
  game='Twisted: A Steampunk Skirmish Game',
  publisher='Demented Games',
  title='Twisted Companion App: the Official Companion for Twisted, A Steampunk Skirmish Game',
  meta='The official companion app for Twisted: A Steampunk Skirmish Game by Demented Games. Company Builder, all 66 characters, 72 virtual cards, the full 10-mission campaign and 12 searchable rule sections, offline.',
  accent='#D9A441', accent2='#F0CE7A', glow='rgba(217,164,65,.30)', tint='#16130B',
  eyebrow='Official Companion App',
  h1='Twisted<br><span class="nw">Companion App</span>',
  tagline='The whole world of Twisted, in your pocket.',
  lede='The official companion app for Twisted: A Steampunk Skirmish Game by Demented Games. Build your Company, check the rules, look up any character, track the fight and dig into the lore, all from your phone at the table or on the go.',
  pills=['Works offline', 'Game Mode', 'Optional sync'],
  apple='https://apps.apple.com/app/twisted-companion-app/id6782623059',
  play='https://play.google.com/store/apps/details?id=com.digirunestudios.twisted',
  icon='../assets/icon-twisted.webp',
  feature='../assets/apps/twisted-feature.webp',
  video='../twisted-demo.mp4', poster='../twisted-demo-poster.jpg',
  shots=[
   ('twisted-shot-1', 'Everything Twisted, in one app'),
   ('twisted-shot-2', 'Every rule, at your fingertips'),
   ('twisted-shot-3', 'Every character, every stat'),
   ('twisted-shot-4', 'Master the Alchemancy'),
   ('twisted-shot-5', 'Build your Company'),
   ('twisted-shot-6', 'Mission setup at your fingertips'),
   ('twisted-shot-7', 'Track your campaign'),
  ],
  kicker='Twisted',
  inside_title="What's inside",
  inside=[
   ('Company Builder', 'Assemble and manage your Company with live points and budget tracking. Keep up to three separate Companies saved and switch between them in a tap.'),
   ('66 Characters', 'The full roster, with stats, weapons, abilities and background lore for every fighter across the Dickensians, the Scions of the Sands, the Guild of Harmony and the Servants of The Engine.'),
   ('182 Abilities and 40 Alchemancy Invocations', 'Tap-to-look-up cross-referencing across the entire roster, so you never have to stop and flip through a book mid-game.'),
   ('72 Virtual Cards', 'Three complete decks: Eye of The Engine (34 cards), Canopic Jars (20) and the Tarot of Taxing Tasks (18). Draw, shuffle and track in the app.'),
   ('80 Delights', 'Search, reference and add Delights to your Company, with budget tracking as you build.'),
   ('Missions and Campaign', 'Mission setup references plus the full 10-mission narrative campaign, with VP tracking across all four acts.'),
  ],
  tools_title='More for the table',
  tools=[
   ('20 Fascinating Features', 'Terrain features with a built-in D20 roller.'),
   ('Combat Tracker', 'Keep the state of the fight in front of you while you play.'),
   ('Dice and Rules', 'Built-in dice plus 12 searchable rule sections for fast table-side lookups.'),
   ('Deep World Lore', 'The history, the factions, and the city in the grip of The Engine.'),
  ],
  built_title='Made for the table',
  built=[
   'Works offline once loaded, so no signal is needed at game night.',
   'Game Mode hides the non-gameplay tabs, so only what you need is on screen.',
   'Fast search with instant term lookup: jump straight to any character, ability or rule.',
   'Optional one-tap sign-in syncs your saved Companies across devices. The app works fully without an account.',
  ],
  extra=('Secrets within The Engine', 'Hidden inside this app is exclusive lore straight from the publisher, revelations you won’t find in any rulebook. But The Engine does not surrender its knowledge freely. Those who wish to find it must first seek it out.'),
  credit='Twisted Companion App is an official product built in partnership with Demented Games. Twisted, its characters, and artwork are the property of their respective owners.',
 ),
}
